name: CI - Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test values length
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install Npm Dependencies
        run: yarn install
      - name: Run jest with CI option
        run: yarn test